version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432' # Mapeia a porta 5432 do container para a máquina host

volumes:
  postgres_data:
