version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${PG_USER}
      DB_PASSWORD: ${PG_PASSWORD}
      DB_NAME: ${PG_DATABASE}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm start

volumes:
  postgres_data:
