name: Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for server
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Altere para a versão que você está usando

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Run server tests
        run: |
          cd server
          npm test

  web-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js for web
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Altere para a versão que você está usando

      - name: Install web dependencies
        run: |
          cd web
          npm install

      - name: Run web tests
        run: |
          cd web
          npm test
